#for start configuration of server port
server:
  port: 8090
spring:
  application:
    name: "employees"
  datasource:
    url: jdbc:h2:mem:testdb
    username: pg
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - application_qa.yml
      - application_prod.yml
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: 3.0.0
